scheduler:
        build: .
        volumes:
                - ./scheduler:/app
        ports:
                - "3000:3000"
        links:
                - postgres
postgres:
        image: postgres:9.4
        ports:
                - "5432"
