db:
        image: postgres:9.4
        ports:
                - "5432"
scheduler:
        build: .
        volumes:
                - ./scheduler:/app
        ports:
                - "3000:3000"
        environment:
                DATABASE_URL: "postgresql://postgres@schedulerdockerised_db_1/"

